[package]
name = "bedrock"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.216", features = ["derive"] }
thiserror = "2.0.11"
toml_edit = { version = "0.22.22", features = ["serde"] }
tokio = { version = "1.42.0", features = ["fs"], optional = true }
miette = { version = "7.4.0", features = ["fancy"] }
ron = "0.8.1"

[dev-dependencies]
bedrock = { path = ".", features = ["tokio"] }
tokio = { version = "1.42.0", features = ["full"] }
