[package]
name = "packet"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.216", features = ["derive"] }
thiserror = "2.0.11"
toml = "0.8.19"

[dev-dependencies]
tempfile = "3.15.0"
