# Specify information about the packet itself
title = "Example Packet"
preamble = '''
This packet includes problems of a difficulty *vastly*
surpassing the capabilities of the average computer
science student. Be wary as these problems will
certainly give you great intellectual trouble. There
is little hope for anyone without a Ph.D in computer
science.

If you decide to attempt these problems anyways, good
luck. You will be rewarded for swiftness in your answers.
'''

[setup]
#import = "./setup.toml"
#import_install = "./install.sh"
#import_init = "./init.sh"
install = '''
apt-get install opam
'''

init = '''
opam init -y
eval $(opam env)
'''

[languages]
python3 = "enabled"
ocaml = { compile = "ocamlc -o out {{SOURCEFLIE}}", run = "./out" }
default = "python3"

default_language = "Python312"
languages = ["Python3XX", "JavaXX", "JavaScript", "TypeScript"]

[[authentication.admins]]
name = "Teacher"
password = "abc123"

[[authentication.participants]]
name = "StudentOne"
password = "123abc"

[[authentication.participants]]
name = "StudentTwo"
password = "deadbeef"

[[problems]]
title = "Reversing a string"
description = '''
Reversing a string is one of the most *basic* algorithmic
problems for a beginner computer science student to solve.

Solve it.
''''

[[problems.tests]]
input = "hello"
output = "olleh"
visible = true

[[problems.tests]]
input = "world"
output = "dlrow"
visible = true

[[problems.tests]]
input = ""
output = ""

[[problems.tests]]
input = "aa"
output = "aa"

[[problems.tests]]
input = "racecar"
output = "racecar"
